name: Test Automation Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily run

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test
      
    - name: Run API tests
      run: ./gradlew apiTests -Dbrowser=${{ matrix.browser }}
      continue-on-error: true
      
    - name: Run Web tests
      run: ./gradlew webTests -Dheadless=true -Dbrowser=${{ matrix.browser }}
      continue-on-error: true
      
    - name: Generate Allure Report
      if: always()
      run: ./gradlew allureReport
      
    - name: Upload Allure Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-results-${{ matrix.browser }}
        path: build/allure-results
        
    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report-${{ matrix.browser }}
        path: build/reports/allure-report
