name: Run All Tests

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test
      
    - name: Run API tests
      run: ./gradlew apiTests
      continue-on-error: true
      
    # No artifact upload in this job to keep it simple
  
  web-tests:
    runs-on: ubuntu-latest
    needs: api-tests  # Run after API tests complete
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test
      
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Run Web UI tests
      run: ./gradlew webTests -Dheadless=true -Dbrowser=chrome
      continue-on-error: true
      
    # No artifact upload in this job to keep it simple
