name: Run All Tests

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Detect UTF-8 BOMs
      run: |
        if grep -rl $'\xEF\xBB\xBF' --include="*.java" --include="*.gradle" --include="*.yml" .; then
          echo "BOM found - please remove"; exit 1;
        fi
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test --warning-mode all
      
    - name: Run API tests
      run: ./gradlew apiTests
      continue-on-error: true
      
    - name: List API report files
      if: always()
      run: |
        echo 'Available API Report Files:'
        find build/reports/cucumber/api -type f -name "*.html" | sort
        
    - name: Upload API Cucumber Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cucumber-api-reports
        path: build/reports/cucumber/api
        retention-days: 7
  
  web-tests:
    runs-on: ubuntu-latest
    needs: api-tests  # Run after API tests complete - Preserving your original structure
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Detect UTF-8 BOMs
      run: |
        if grep -rl $'\xEF\xBB\xBF' --include="*.java" --include="*.gradle" --include="*.yml" .; then
          echo "BOM found - please remove"; exit 1;
        fi
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test --warning-mode all
      
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Run Web UI tests
      run: ./gradlew webTests -Dheadless=true -Dbrowser=chrome
      continue-on-error: true
      
    - name: List Web report files
      if: always()
      run: |
        echo 'Available Web Report Files:'
        find build/reports/cucumber/web -type f -name "*.html" | sort
        
    - name: Upload Web Cucumber Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cucumber-web-reports
        path: build/reports/cucumber/web
        retention-days: 7
