name: Run All Tests

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  all-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test
      
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Run API tests
      run: ./gradlew apiTests
      id: api-tests
      continue-on-error: true
      
    - name: Run Web UI tests
      run: ./gradlew webTests -Dheadless=true -Dbrowser=chrome
      id: web-tests
      if: always()
      continue-on-error: true
      
    - name: Generate Test Summary
      if: always()
      run: |
        echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "API Tests: ${{ steps.api-tests.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "Web Tests: ${{ steps.web-tests.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
    - name: Upload API Cucumber Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cucumber-api-reports
        path: build/reports/cucumber/api
        retention-days: 7
        
    - name: Upload Web Cucumber Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cucumber-web-reports
        path: build/reports/cucumber/web
        retention-days: 7
        
    - name: Upload Combined Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: all-test-reports
        path: build/reports/cucumber
        retention-days: 7
        
    - name: Fail job if tests failed
      if: always()
      run: |
        if [[ "${{ steps.api-tests.outcome }}" == "failure" ]] || [[ "${{ steps.web-tests.outcome }}" == "failure" ]]; then
          echo "One or more test suites failed"
          exit 1
        fi
