name: API Tests

on:
  workflow_dispatch:  # Manual trigger
  pull_request:       # Run on pull requests
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Detect UTF-8 BOMs
      run: |
        if grep -rl $'\xEF\xBB\xBF' --include="*.java" --include="*.gradle" --include="*.yml" .; then
          echo "BOM found - please remove"; exit 1;
        fi
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test --warning-mode all
      
    - name: Run API tests
      run: ./gradlew apiTests
      continue-on-error: true
      
    - name: List report files
      if: always()
      run: |
        echo 'Available Report Files:'
        find build/reports/cucumber/api -type f -name "*.html" | sort