name: Web UI Tests

on:
  workflow_dispatch:  # Manual trigger
  pull_request:       # Run on pull requests
    branches: [ main ]

jobs:
  web-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test
      
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Run Web UI tests
      run: ./gradlew webTests -Dheadless=true -Dbrowser=chrome
      continue-on-error: true
      
    - name: Create reports directory if it doesn't exist
      run: mkdir -p build/reports/cucumber/web
      
    - name: Upload Cucumber Reports
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: cucumber-web-reports
        path: build/reports/cucumber/web
