name: Web UI Tests

on:
  workflow_dispatch:  # Manual trigger
  pull_request:       # Run on pull requests
    branches: [ main ]

jobs:
  web-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test
      
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Run Web UI tests with retry
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: ./gradlew webTests -Dheadless=true -Dbrowser=chrome
        
    - name: Upload Cucumber Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-web-reports
        path: |
          build/reports/cucumber/web/
          build/reports/cucumber-html-reports/
        retention-days: 7
